# Search Terms with Pandas #
In this lab we are analyzing the difference between storing and manipulating a significant amout of data using, python lists and using Pandas. 
The same data was used from Direct-Supply as in Lab 2, and it is a list of words and codes that were searched for on thier website. The  program shows this data being cleaned of various elements and being stored into the dataframe. 

coded by: Cherise Malisa

In the following cell the searchTerms file is opened and the  first column of data from the file is input into an array called search_phrases.

In [1]:
%%time
import sklearn.ensemble as mdl
import pandas as pd
import numpy as np
from spellchecker import SpellChecker

search_phrases = []
with open('searchTerms.csv', encoding = 'UTF-8') as f:
    f.readline()
    for line in f:
        search_phrases.append(line.split(',')[0])

Wall time: 8.28 s

This method splits each phrase given from the previously created array list, into seperate words and places those into a list.

In [2]:
def spliiting_phrases(search_phrases):
    """
    This function splits each phrase into sepearate words
     :param list search_phrases: the search phrases read in from the provided database
     :return: a list of tokens with the split phrases as seperate words
    """
    
    tokens = []
    for x in search_phrases:
        if " " in x:
            tokens += x.split(' ')
        else:
            tokens.append(x)
    return tokens

In [3]:
split_tokens = spliiting_phrases(search_phrases)

In the following cell, a dataframe is created and the list of tokens(uncleaned) is populated into the rows of the column with the heading "uncleaned_tokens".

In [4]:
df = pd.DataFrame(split_tokens, columns=['uncleaned_tokens'])

# print(df)

This method removes any %20 otherwise known as web-spaces and replaces it with a space. Then the proper word is put into a list of cleaned tokens.

In [5]:
def cleaning_tokens(split_tokens):
    """
    This function removes any %20 otherwise known as web-spaces.
    :param list split_tokens: the list of search phrases split into sepearate tokens.
    :return: list of tokens with no webspaces in any of the words
    """
    clean_tokens = []
    for x in split_tokens:
        if '%20' in x:
            clean_tokens.append(x.replace('%20',' '))

        else:
            clean_tokens.append(x)

    return clean_tokens

In the cell below the cleaned tokens are then placed into a DataFrame into a column"no-web-spaces"

In [6]:
clean_tokens = cleaning_tokens(split_tokens)
df = pd.DataFrame(clean_tokens, columns = ['no web-spaces'])
# print(df.head(60))

The next cell has a function that takes in a word and removes punctuation marks from that word.

In [7]:
import string

def punctutation_removal(word):
    """
    This function removes all the punctuation marks a word
    :param string word: a word from the dataframe column that may have punctuation marks in it
    :return: word with punctuation marks removed from it.
    """
    translation2 = str.maketrans('','',string.punctuation)
    without_punct = word.translate(translation2)
    
    return without_punct

The cell below applies the previous function to a specified column in the DataFrame that was created.

In [8]:
column = df['no web-spaces']
converted = column.map(lambda x: punctutation_removal(x))
# converted.head(60)
df["punct_removed"] = converted
# df.head(60)

In [9]:
import string

def number_removal(word):
    """
    This function removes all numbers in a token 
    :param string word: a word from the dataframe column that may have punctuation marks in it
    :return: word with no number in it.
    """
    translation = str.maketrans('','',string.digits)
    no_numbers = word.translate(translation)
    
    return no_numbers

In [10]:
column = df['punct_removed']
converted = column.map(lambda x: number_removal(x))
# converted.head(60)
df["numbers_removed"] = converted

df.replace("",np.nan, inplace = True)
df.dropna(subset = ["numbers_removed"], inplace = True)
df.head(60)

    no web-spaces punct_removed numbers_removed
1            CMED          CMED            CMED
3            KEND          KEND            KEND
5            CMED          CMED            CMED
7       DYNC1815H     DYNC1815H           DYNCH
8       DYND70642     DYND70642            DYND
9            DEES          DEES            DEES
10       KC-21400       KC21400              KC
11           LINK          LINK            LINK
12         PC1000        PC1000              PC
14           KEND          KEND            KEND
15         8507SA        8507SA              SA
16           KEND          KEND            KEND
18          bacon         bacon           bacon
19      pineapple     pineapple       pineapple
21     enfit70550    enfit70550           enfit
22         cheese        cheese          cheese
23        cheddar       cheddar         cheddar
28     buttermilk    buttermilk      buttermilk
36           milk          milk            milk
37        chicken       chicken         chicken
38         breast        breast          breast
39           DRIT          DRIT            DRIT
42         romain        romain          romain
43         banana        banana          banana
44           16sl          16sl              sl
45     URO51211CH    URO51211CH           UROCH
46           HUDS          HUDS            HUDS
48          bacon         bacon           bacon
52      name tags     name tags       name tags
54            cut           cut             cut
55          fruit         fruit           fruit
56           HUDS          HUDS            HUDS
58           milk          milk            milk
61        biscuit       biscuit         biscuit
66            way           way             way
71           milk          milk            milk
76           GERI          GERI            GERI
77        HCS4485       HCS4485             HCS
78          bacon         bacon           bacon
79           mash          mash            mash
80         liquid        liquid          liquid
81            egg           egg             egg
84          wipes         wipes           wipes
85     DYND11756H    DYND11756H           DYNDH
86          bacon         bacon           bacon
90        creamer       creamer         creamer
95           HUDS          HUDS            HUDS
97        lettuce       lettuce         lettuce
98          apple         apple           apple
99          sauce         sauce           sauce
101       cottage       cottage         cottage
104          milk          milk            milk
108       lactose       lactose         lactose
109          milk          milk            milk
113         JUICE         JUICE           JUICE
114           ORG           ORG             ORG
115          milk          milk            milk
116       biscuit       biscuit         biscuit
117       creamer       creamer         creamer
121       bottled       bottled         bottled

In [11]:
from spellchecker import SpellChecker

spell = SpellChecker(distance = 1)

def spell_correction(column, word_df):
    """
    """
    spell_checking_dictionary = {}
    
    misspelled_words_token = []
   
    correct_spelling = spell.correction(word_df.lower())

    return correct_spelling

In [12]:
column_as_list = df["numbers_removed"].to_list()
column = df["numbers_removed"]

converted = column.map(lambda x: spell_correction(column_as_list, x))
df["correct_spellings"] = converted
# converted.head(60)
df.head(60)
# remeber to make a dictionary 
# correct_spelling_dict = df.to_dict(numbers_removed,correct_spellings)

    no web-spaces punct_removed numbers_removed correct_spellings
1            CMED          CMED            CMED               med
3            KEND          KEND            KEND              kind
5            CMED          CMED            CMED               med
7       DYNC1815H     DYNC1815H           DYNCH             lynch
8       DYND70642     DYND70642            DYND              dyed
9            DEES          DEES            DEES              dees
10       KC-21400       KC21400              KC                ke
11           LINK          LINK            LINK              link
12         PC1000        PC1000              PC                pa
14           KEND          KEND            KEND              kind
15         8507SA        8507SA              SA                sa
16           KEND          KEND            KEND              kind
18          bacon         bacon           bacon             bacon
19      pineapple     pineapple       pineapple         pineapple
21     enfit70550    enfit70550           enfit             unfit
22         cheese        cheese          cheese            cheese
23        cheddar       cheddar         cheddar           cheddar
28     buttermilk    buttermilk      buttermilk        buttermilk
36           milk          milk            milk              milk
37        chicken       chicken         chicken           chicken
38         breast        breast          breast            breast
39           DRIT          DRIT            DRIT              dirt
42         romain        romain          romain            romain
43         banana        banana          banana            banana
44           16sl          16sl              sl                so
45     URO51211CH    URO51211CH           UROCH            urdoch
46           HUDS          HUDS            HUDS              hugs
48          bacon         bacon           bacon             bacon
52      name tags     name tags       name tags          nametags
54            cut           cut             cut               cut
55          fruit         fruit           fruit             fruit
56           HUDS          HUDS            HUDS              hugs
58           milk          milk            milk              milk
61        biscuit       biscuit         biscuit           biscuit
66            way           way             way               way
71           milk          milk            milk              milk
76           GERI          GERI            GERI              geri
77        HCS4485       HCS4485             HCS               his
78          bacon         bacon           bacon             bacon
79           mash          mash            mash              mash
80         liquid        liquid          liquid            liquid
81            egg           egg             egg               egg
84          wipes         wipes           wipes             wipes
85     DYND11756H    DYND11756H           DYNDH             dyndh
86          bacon         bacon           bacon             bacon
90        creamer       creamer         creamer           creamer
95           HUDS          HUDS            HUDS              hugs
97        lettuce       lettuce         lettuce           lettuce
98          apple         apple           apple             apple
99          sauce         sauce           sauce             sauce
101       cottage       cottage         cottage           cottage
104          milk          milk            milk              milk
108       lactose       lactose         lactose           lactose
109          milk          milk            milk              milk
113         JUICE         JUICE           JUICE             juice
114           ORG           ORG             ORG               org
115          milk          milk            milk              milk
116       biscuit       biscuit         biscuit           biscuit
117       creamer       creamer         creamer           creamer
121       bottled       bottled         bottled           bottled

In [13]:
def frequency_count_listmethod(datalist):
    
    term_frequency = {}
    
    unique_words = set(datalist)
    for words in unique_words:
        term_frequency[words] = datalist.count(words)
        
    return term_frequency

In [14]:
%%time
correct_list = df["correct_spellings"].to_list()
frequency_for_list = frequency_count_listmethod(correct_list)

Wall time: 17min 47s

In [15]:
%%time
frequency_for_df = df["correct_spellings"].value_counts()
print(frequency_for_df.head(60))

chicken      18331
cream        15214
cheese       13307
beef         12971
pie          10960
juice        10870
sauce        10817
pork         10646
potato        9835
green         9392
diced         9159
beans         8707
tomato        8599
corn          7927
apple         7503
bread         7438
sausage       7175
i             6911
cake          6712
mix           6670
turkey        6286
sugar         6224
rice          6220
onion         6200
bacon         6177
bean          6070
salad         5704
egg           5695
orange        5480
fruit         5376
ham           5285
butter        5034
mic           4960
garlic        4957
brown         4942
lemon         4855
paper         4831
pepper        4754
milk          4641
base          4596
roll          4537
honey         4433
ot            4273
soup          4254
broccoli      4101
steak         4074
red           3998
banana        3931
gravy         3928
cranberry     3908
french        3885
non           3883
patty         3843
sliced        3824
sour          3809
peas          3794
water         3766
tea           3762
italian       3745
ground        3638
Name: correct_spellings, dtype: int64
Wall time: 380 ms

### Runtime Comparision ###
python list time: 8mins 9s
DataFrame count time: 346 ms
The python lists takes a greater time to run than the data frame count method. This could be because the list is really long and it has to be iterated through first, and then for each word it will get the freqeuncy count by going through the whole list again and counting how many times the word appears. And with the DataFRame it has an effeiceint built in method that does this, and the time it takes is soo much shorter than that of a regular python list with iteration and count(). 
In conclusion for a very large amount of data the dataFrame value_counts approach is the best. As it takes a good amount of time to run and the python list method is very slow for a computer method/function.

In [16]:
import sys
# df.memory_usage(deep= True)
total_size = 0
for x in correct_list:
    total_size += sys.getsizeof(x)
print(total_size)

69978935

In [17]:
df["correct_spellings"].memory_usage(deep= True)

90454647

### Memory usage ###
The memory usage for the list is much smaller than that of the data frame. This could be because it is just one particular list and not multiple whereas with the DAtaframe all the columns can be taught of as being lists and so a whole dataframe has multiple lists. I am surprised that the data frame used more memory, i just assumed that if it is more effeicient in terms of runtime it would be effiecient in terms of memory as well.

## Conclusion ##
Advantages of using Pandas: With regards to using pandas from a userability standpoint, It is easier to use. Easier to amnipulate the data when it is in column using functions than with other data types when the data is of a large quantity. It is also  helps with keeping the program clean and this makes data easier to analyse and compare than with normal python data structures.Performance wise pandas takes less time to run as with using python list methods to sort and clean the data as required.

Disadvantages of using Pandas: if you want to view the whole dataframe column of data thats very large you can not because it will givde a summarsied output unless you specify you want to view 60 rows for the columns you have for example.Otherwise I found no other disadvantages